from enum import StrEnum


class EventSlug(StrEnum):
    EVENT_2x2 = "222"
    EVENT_3x3 = "333"
    EVENT_4x4 = "444"
    EVENT_5x5 = "555"
    EVENT_6x6 = "666"
    EVENT_7x7 = "777"
    EVENT_3x3OH = "3oh"
    SQUARE_1 = "sq1"
    PYRAMINX = "pyra"
    MEGAMINX = "mega"
    SKEWB = "skewb"
    CLOCK = "clock"
    FMC = "fmc"
    THREE_BLD = "3bld"
    FOUR_BLD = "4bld"
    FIVE_BLD = "5bld"
    MBLD = "mbld"
    FTO = "fto"
    MIRROR_BLOCKS = "bump"
    KILOMINX = "kilo"
    EVENT_4x4OH = "4oh"
    THREE_BY_THREE_TWO = "332"
    THREE_BY_THREE_FOUR = "334"
    THREE_BY_THREE_FIVE = "335"
    TWO_BY_TWO_BY_THREE = "223"
    RELAY_2_3_4 = "234relay"
    RELAY_3x3x3 = "333relay"
    REDI_CUBE = "redi"
    DINO_CUBE = "dino"
    REX_CUBE = "rex"
    FIFTEEN_PUZZLE = "15puzzle"
    EVENT_8x8 = "888"
    EVENT_9x9 = "999"
    EVENT_10x10 = "10x"
    BICUBE = "bicube"
