from enum import StrEnum


class EventSlug(StrEnum):
    EVENT_2x2 = "2x2"
    EVENT_3x3 = "3x3"
    EVENT_4x4 = "4x4"
    EVENT_5x5 = "5x5"
    EVENT_6x6 = "6x6"
    EVENT_7x7 = "7x7"
    EVENT_3x3OH = "3x3oh"
    SQUARE_1 = "sq1"
    PYRAMINX = "pyra"
    MEGAMINX = "mega"
    SKEWB = "skewb"
    CLOCK = "clock"
    FMC = "fmc"
    THREE_BLD = "3bld"
    FOUR_BLD = "4bld"
    FIVE_BLD = "5bld"
    MBLD = "mbld"
    FTO = "fto"
    VOID_CUBE = "void"
    MIRROR_BLOCKS = "bump"
    KILOMINX = "kilo"
    EVENT_4x4OH = "4x4oh"
    THREE_BY_THREE_TWO = "332"
    THREE_BY_THREE_FOUR = "334"
    THREE_BY_THREE_FIVE = "335"
    TWO_BY_TWO_BY_THREE = "223"
    RELAY_2_3_4 = "234relay"
    RELAY_3x3x3 = "333relay"
    TWO_BLD = "2bld"
    REDI_CUBE = "redicube"
    DINO_CUBE = "dinocube"
    REX_CUBE = "rexcube"
    PUZZLE_15 = "15"
    EVENT_8x8 = "8x8"
    EVENT_9x9 = "9x9"
    EVENT_10x10 = "10x10"
    BICUBE = "bicube"
